### PR TITLE
Jason Diep Coding Challenge Rubyonrails

### PR DESCRIPTION
**Pull request by chairwood**
This challenge was completed with Ruby on Rails and can be access by multiple users. It covers the validation for uniqueness and numericality. Thank you for reviewing this!

### CODE REVIEW

**Comment by Fingel** [comment]
Hi Jason,
The instructions mention providing a SETUP file. Could you write one detailing how to get this application up and running? Thanks!

**Comment by chairwood** [comment]
Austin:

Yes I do see that in the instructions. Sorry I accidentally skipped over
that. I've never made a SETUP file before but I'll look into that right
now. Thanks!


-Jason

**Comment by chairwood** [comment]
Austin:

I wasn't able to figure out how to create a SETUP file. But as for how to
set up the Ruby on Rails environment. I have a ran "gem install bundler"
and run "bundle install". For running the server, I started up a local
server with "rails s" command. Sorry I wasn't able to figure it out.


-Jason

**Comment by Fingel** [comment]
Hi Jason,
There is no specific way to write a SETUP file. It's just a file that describes how to run your project, just like you did in your last reply. This is so people who aren't familiar with ruby or rails can get up and running without too much guesswork.

**Pull request closed without merging**
