### PR TITLE
takehome

### PR DESCRIPTION
**Pull request by bzuhair**

### CODE REVIEW

**Review by bzuhair — COMMENTED** [review]
In case it wasn't clear in the terminal run 'npm install' and then 'npm start'. The app should then be running on http://localhost:3000/.

**Comment by Fingel** [comment]
Hi,
Thanks for your submission.

Prior to your latest commit, there was no indication in the Setup file what port the server listed on, so I had to hunt through the code to find that, and found that it was on 3000.

Once the form loaded, I attempted to add a planet. When clicking submit, the page reloads but nothing else happens. I tried figuring out what might be wrong, but was unable.

I noticed you're including a beta version of jquery that was released several years ago. Maybe using a production ready version might help?

**Comment by bzuhair** [comment]
That's weird it works find with the beta version on my end but I'll update the code and send in another pull request. Aside from that when you click submit does an error pop up in the terminal? If so could you send the error.

**Comment by markBowman** [comment]
Hi Balal,
Thank you for your submission. We do appreciate you finding the time to complete the code challenge. I'm sure with a little effort we could get your code working (it seems to work in Chrome but not in Firefox). Getting the code working is just one of the criteria we use to make a decision. Other criteria are code style and attention to detail. I'm afraid in this instance you did not meet the minimum score to proceed to the next stage, but I would encourage you to apply again the future.
Thank you,
Mark Bowman

**Comment by bzuhair** [comment]
Austin and Mark
Ok. Thank you for taking the time to look over my solution.
Balal

**Pull request closed without merging**
